n_workers: 0
n_epochs_generalized: 100
n_epochs_prior: 1000
gan_size: 128
channel_multiplier: 1
image_size: 128
z_dim: 512
category: face
gan_ckpt_path: checkpoints/stylegan2/stylegan2-celeba-config-e.pt
root_path: data/celeba
learning_rate: 0.0001
view_scale: 1
n_proj_samples: 16
batch_size: 32
prior_name: smoothed_box
image_subset: [0,1,2]
## View-Light sampler checkpoints
view_mvn_path: checkpoints/view_light/view_mvn.pth
light_mvn_path: checkpoints/view_light/light_mvn.pth

our_nets_ckpts:
  VLADE_nets: checkpoints/our_nets
  other: '?'

## renderer
rot_center_depth: 1.0
fov: 10  # in degrees
tex_cube_size: 2

