n_workers: 0
n_epochs_prior: 1000
batch_size: 164
gan_size: 512
channel_multiplier: 2
image_size: 128
z_dim: 512
category: car
gan_ckpt_path: checkpoints/stylegan2/stylegan2-car-config-f.pt
root_path: data/car
learning_rate: 0.0001
view_scale: 1
refinement_iterations: 1
n_proj_samples: 2
prior_name: ellipsoid
stylegan_compatibility_mode: False  # use original implementation of stylegan2
stylegan3: True  # use of stylegan2/stylegan3 (new implementation)

## View-Light sampler checkpoints
view_mvn_path: checkpoints/view_light/view_mvn.pth
light_mvn_path: checkpoints/view_light/light_mvn.pth

our_nets_ckpts:
  VLADE_nets: checkpoints/our_nets/
  other: '?'

## renderer
rot_center_depth: 1.0
fov: 10  # in degrees
tex_cube_size: 2

