n_workers: 0
n_epochs_generalized: 10
n_epochs_prior: 1000
gan_size: 512
channel_multiplier: 2
image_size: 128
z_dim: 512
category: cat
gan_ckpt_path: https://api.ngc.nvidia.com/v2/models/nvidia/research/stylegan2/versions/1/files/stylegan2-afhqcat-512x512.pkl
root_path: data/cat
learning_rate: 0.0001
view_scale: 1
refinement_iterations: 1
n_proj_samples: 2
batch_size: 2
prior_name: ellipsoid
stylegan_compatibility_mode: False  # use original implementation of stylegan2
stylegan3: False  # use of stylegan2/stylegan3 (new implementation)

## View-Light sampler checkpoints
view_mvn_path: checkpoints/view_light/view_mvn.pth
light_mvn_path: checkpoints/view_light/light_mvn.pth

our_nets_ckpts:
  VLADE_nets: checkpoints/our_nets/
  other: '?'

## renderer
rot_center_depth: 1.0
fov: 10  # in degrees
tex_cube_size: 2

